# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

skip_docs

platform :android do
  lane :release do |options|
    gradle(
      task: "clean"
    )

    gradle(
      task: 'androidDependencies',
      print_command: false
    )

    build_android_app(
      task: 'assemble',
      flavor: options[:flavor],
      build_type: 'Release',
      print_command: false,
    )

    upload_to_play_store(
      track: options[:track]
    )
  end

  lane :debug do |options|
    increment_version_code(
      gradle_file_path: “app/build.gradle.kts”
    )

    gradle(
      task: "clean"
    )

    gradle(
      task: 'androidDependencies',
      print_command: false
    )

    build_android_app(
      task: 'assemble',
      flavor: options[:flavor],
      build_type: 'Debug',
      print_command: false,
    )

# Do something with the apk
  end
end
