# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

skip_docs

platform :android do
  lane :deploy_production do
    release(flavor: 'Prod', track: 'internal')
  end

  lane :deploy_dev do
    release(flavor: 'Dev', track: 'internal')
  end

  lane :deploy_staging do
    release(flavor: 'Staging', track: 'internal')
  end

  lane :debug_production do
      debug(flavor: 'Prod')
  end

  lane :debug_dev do
    debug(flavor: 'Dev')
  end

  lane :debug_staging do
    debug(flavor: 'Staging')
  end

  lane :release do |options|
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )

    gradle(
      task: "clean"
    )

    gradle(
      task: 'androidDependencies',
      print_command: false
    )

    build_android_app(
      task: 'assemble',
      flavor: options[:flavor],
      build_type: 'Release',
      print_command: false,
    )

    upload_to_play_store(
      track: options[:track]
    )
  end

  lane :debug do |options|
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )

    gradle(
      task: "clean"
    )

    gradle(
      task: 'androidDependencies',
      print_command: false
    )

    build_android_app(
      task: 'assemble',
      flavor: options[:flavor],
      build_type: 'Debug',
      print_command: false,
    )

# Do something with the apk
  end
end
